<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);NU5128;</NoWarn>
    <Description>Base class and C# code helpers for preprocessed T4 text templates that generate code from input data.</Description>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <PackageTags>t4;text-templating;code-generation;source-generator;csharp</PackageTags>
    <MSKit_PackageReadmeSourcePath>$(MSBuildThisFileDirectory)../../README.md</MSKit_PackageReadmeSourcePath>
  </PropertyGroup>
</Project>
