<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Verify" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.XunitV3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DragoAnt.Extensions.T4\DragoAnt.Extensions.T4.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".verify.expected\*.cs" />
    <None Update="TestTemplate.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>TestTemplate.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="TestTemplate.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TestTemplate.tt</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
