// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DragoAnt.Extensions.T4.Tests
{
    using DragoAnt.Extensions.T4;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class TestTemplate : BaseTransformation<TemplateTestData>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Data.Namespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\ninternal static class TestClass\r\n{\r\n    public static int[] Property => [");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Data.Numbers)));
            
            #line default
            #line hidden
            this.Write("];\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
