<Project>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TargetFramework Condition="$(MSBuildProjectName.EndsWith('.Tests'))">net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1062;CA1711;</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Copyright>Copyright (c) 2024 DragoAnt</Copyright>
    <Product>T4 Extensions</Product>
    <MSKit_TestsAssertions>None</MSKit_TestsAssertions>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory).toolkit/msbuild/init.props" />

</Project>
