<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Verify" Version="33.2.0" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.4.0" />
    <PackageVersion Include="Verify.XunitV3" Version="32.0.0" />
  </ItemGroup>
</Project>
